import { COLOR_LIGHT } from '@ui/theme/constants/ColorsLight';

export const TAG_LIGHT = {
  text: {
    gray: COLOR_LIGHT.gray11,
    mauve: COLOR_LIGHT.mauve11,
    slate: COLOR_LIGHT.slate11,
    // PROPEL-NOCTURNE PATCH (Tier B) — warm semantic set (DESIGN.md §2.1,
    // light column): sage #4F7A46, amber #9A7A2E, red -> terracotta #B23A2A.
    sage: 'color(display-p3 0.31 0.478 0.275)',
    olive: COLOR_LIGHT.olive11,
    sand: COLOR_LIGHT.sand11,
    tomato: COLOR_LIGHT.tomato11,
    red: 'color(display-p3 0.698 0.227 0.165)',
    ruby: COLOR_LIGHT.ruby11,
    crimson: COLOR_LIGHT.crimson11,
    pink: COLOR_LIGHT.pink11,
    plum: COLOR_LIGHT.plum11,
    purple: COLOR_LIGHT.purple11,
    violet: COLOR_LIGHT.violet11,
    iris: COLOR_LIGHT.iris11,
    cyan: COLOR_LIGHT.cyan11,
    turquoise: COLOR_LIGHT.turquoise11,
    sky: COLOR_LIGHT.sky11,
    blue: COLOR_LIGHT.blue11,
    jade: COLOR_LIGHT.jade11,
    green: COLOR_LIGHT.green11,
    grass: COLOR_LIGHT.grass11,
    mint: COLOR_LIGHT.mint11,
    lime: COLOR_LIGHT.lime11,
    bronze: COLOR_LIGHT.bronze11,
    gold: COLOR_LIGHT.gold11,
    brown: COLOR_LIGHT.brown11,
    orange: COLOR_LIGHT.orange11,
    amber: 'color(display-p3 0.604 0.478 0.18)',
    yellow: COLOR_LIGHT.yellow11,
  },
  background: {
    gray: COLOR_LIGHT.gray3,
    mauve: COLOR_LIGHT.mauve3,
    slate: COLOR_LIGHT.slate3,
    // PROPEL-NOCTURNE PATCH (Tier B) — soft washes of the warm semantic set.
    sage: 'color(display-p3 0.31 0.478 0.275 / 0.12)',
    olive: COLOR_LIGHT.olive3,
    sand: COLOR_LIGHT.sand3,
    tomato: COLOR_LIGHT.tomato3,
    red: 'color(display-p3 0.698 0.227 0.165 / 0.12)',
    ruby: COLOR_LIGHT.ruby3,
    crimson: COLOR_LIGHT.crimson3,
    pink: COLOR_LIGHT.pink3,
    plum: COLOR_LIGHT.plum3,
    purple: COLOR_LIGHT.purple3,
    violet: COLOR_LIGHT.violet3,
    iris: COLOR_LIGHT.iris3,
    cyan: COLOR_LIGHT.cyan3,
    turquoise: COLOR_LIGHT.turquoise3,
    sky: COLOR_LIGHT.sky3,
    blue: COLOR_LIGHT.blue3,
    jade: COLOR_LIGHT.jade3,
    green: COLOR_LIGHT.green3,
    grass: COLOR_LIGHT.grass3,
    mint: COLOR_LIGHT.mint3,
    lime: COLOR_LIGHT.lime3,
    bronze: COLOR_LIGHT.bronze3,
    gold: COLOR_LIGHT.gold3,
    brown: COLOR_LIGHT.brown3,
    orange: COLOR_LIGHT.orange3,
    amber: 'color(display-p3 0.604 0.478 0.18 / 0.12)',
    yellow: COLOR_LIGHT.yellow3,
  },
};
